Algoritmo "Caixa_de_supermercado"

Var
valores: real
nomeCliente: caracter
produto: inteiro
valorFinal: real


Inicio
escreval("Bem vindo ao supermercado Andorinha!")

escreval("Escreva seu nome:")
leia()

para produto de 1 até 5 faca
escreva("Digite o valor do produto", produto, ":")
leia(valores)

valorFinal <- valores + valorFinal
fimpara

escreval("Valor Final:", valorFinal)

Fimalgoritmo